##################################################################
#
## FILENAME    - Makefile
#
## DESCRIPTION - Advanced Parallel Computing, SS15 HD, Sheet 7
#
## AUTHOR      - Naumann, Klein
#
## LAST CHANGE - 2015-06-09
#
##################################################################

CC=gcc
#CFLAGS = -pthread

redblacktree:
	$(CC) src/main.c src/rbtree.c -o redblacktree

.PHONY: clean
clean :
	rm -f redblacktree
